In [1]:
import pandas as pd
import numpy as np

C:\Users\raven\AppData\Local\Temp\ipykernel_13772\2162656668.py:1: DeprecationWarning:
Pyarrow will become a required dependency of pandas in the next major release of pandas (pandas 3.0),
(to allow more performant data types, such as the Arrow string type, and better interoperability with other libraries)
but was not found to be installed on your system.
If this would cause problems for you,
please provide us feedback at https://github.com/pandas-dev/pandas/issues/54466

  import pandas as pd

In [2]:
data = pd.read_csv("charging_stations.csv")

In [3]:
clipped_data = data[["full_id", "osm_id", "Y", "X"]]

In [4]:
clipped_data["status"] = 0.0
clipped_data["power"] = 0.0
clipped_data["fast_charging"] = 0.0
clipped_data["cost"] = 0.0
clipped_data["brand"] = 0.0
clipped_data["level"] = 0.0

C:\Users\raven\AppData\Local\Temp\ipykernel_13772\471049472.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  clipped_data["status"] = 0.0
C:\Users\raven\AppData\Local\Temp\ipykernel_13772\471049472.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  clipped_data["power"] = 0.0
C:\Users\raven\AppData\Local\Temp\ipykernel_13772\471049472.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  clipped_data["fast_charging"] = 0.0
C:\Users\raven\AppData\Local\Temp\ipykernel_13772\471049472.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  clipped_data["cost"] = 0.0
C:\Users\raven\AppData\Local\Temp\ipykernel_13772\471049472.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  clipped_data["brand"] = 0.0
C:\Users\raven\AppData\Local\Temp\ipykernel_13772\471049472.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  clipped_data["level"] = 0.0

In [5]:
status = []
for i in range(1685):
    if np.random.randint(2)==0:
        status.append("available")
    else:
        status.append("unavailable")

In [6]:
capacity = []
for i in range(1685):
    capacity.append(np.random.randint(3, 10))

In [7]:
fast_charging = []
for i in range(1685):
    if np.random.randint(2)==0:
        fast_charging.append(True)
    else:
        fast_charging.append(False)

In [8]:
level = []

for i in range(1685):
    if np.random.randint(2)==0:
        level.append("Level 1")
    elif np.random.randint(2)==1:
        level.append("Level 2")
    else:
        level.append("Level 3")

In [9]:
power = []

for i in range(1685):
    if level[i]=="Level 1":
        power.append(120)
    elif level[i]=="Level 2":
        power.append(np.random.randint(208, 240))
    else:
        power.append(480)

In [10]:
charging_brands = ["Begum Energy", "Eticanium Energy", "S4M3T Energy", "Tosuns Energy"]

brand = []

for i in range(1685):
    
    rand_index = np.random.randint(4)
    brand.append(charging_brands[rand_index])

In [11]:
cost = []

for i in range(1685):
    
    cost.append(round(np.random.uniform(0.2, 0.7), 2))

In [12]:
payment_method = []

methods = ["Cash", "Credit Card", "Debit Card", "Others"]

for i in range(1685):
    rand_index = np.random.randint(4)
    payment_method.append(methods[rand_index])

In [13]:
clipped_data["status"] = status
clipped_data["power"] = power
clipped_data["fast_charging"] = fast_charging
clipped_data["cost"] = cost
clipped_data["brand"] = brand
clipped_data["level"] = level

C:\Users\raven\AppData\Local\Temp\ipykernel_13772\1006736820.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  clipped_data["status"] = status
C:\Users\raven\AppData\Local\Temp\ipykernel_13772\1006736820.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  clipped_data["power"] = power
C:\Users\raven\AppData\Local\Temp\ipykernel_13772\1006736820.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  clipped_data["fast_charging"] = fast_charging
C:\Users\raven\AppData\Local\Temp\ipykernel_13772\1006736820.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  clipped_data["cost"] = cost
C:\Users\raven\AppData\Local\Temp\ipykernel_13772\1006736820.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  clipped_data["brand"] = brand
C:\Users\raven\AppData\Local\Temp\ipykernel_13772\1006736820.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  clipped_data["level"] = level

In [14]:
clipped_data

,full_id,osm_id,Y,X,status,power,fast_charging,cost,brand,level
0,n757889531,757889531,7.065273e+06,1.619819e+06,unavailable,120,True,0.41,Begum Energy,Level 1
1,n1272891734,1272891734,6.843462e+06,2.341171e+06,unavailable,120,True,0.40,Tosuns Energy,Level 1
2,n1272891737,1272891737,6.843466e+06,2.341168e+06,unavailable,120,False,0.69,S4M3T Energy,Level 1
3,n1375294622,1375294622,6.834627e+06,2.342684e+06,available,223,False,0.28,S4M3T Energy,Level 2
4,n1692272423,1692272423,6.848312e+06,2.346883e+06,available,221,False,0.67,Begum Energy,Level 2
...,...,...,...,...,...,...,...,...,...,...
1680,n11528393734,11528393734,6.670377e+06,2.505499e+06,available,120,True,0.26,Begum Energy,Level 1
1681,n11533592971,11533592971,6.982196e+06,1.883888e+06,unavailable,480,True,0.45,Begum Energy,Level 3
1682,n11534904116,11534904116,6.668169e+06,2.511348e+06,available,120,False,0.40,Tosuns Energy,Level 1
1683,n11534904117,11534904117,6.668160e+06,2.511357e+06,unavailable,120,True,0.27,Begum Energy,Level 1
1684,n11534904118,11534904118,6.668152e+06,2.511356e+06,unavailable,480,True,0.70,Eticanium Energy,Level 3

In [15]:
import geopandas as gpd

In [16]:
gdf = gpd.GeoDataFrame(
    clipped_data, geometry=gpd.points_from_xy(clipped_data.Y, clipped_data.X), crs="EPSG:3857")

In [17]:
gdf

,full_id,osm_id,Y,X,status,power,fast_charging,cost,brand,level,geometry
0,n757889531,757889531,7.065273e+06,1.619819e+06,unavailable,120,True,0.41,Begum Energy,Level 1,POINT (7065272.641 1619819.261)
1,n1272891734,1272891734,6.843462e+06,2.341171e+06,unavailable,120,True,0.40,Tosuns Energy,Level 1,POINT (6843461.546 2341171.042)
2,n1272891737,1272891737,6.843466e+06,2.341168e+06,unavailable,120,False,0.69,S4M3T Energy,Level 1,POINT (6843466.073 2341167.625)
3,n1375294622,1375294622,6.834627e+06,2.342684e+06,available,223,False,0.28,S4M3T Energy,Level 2,POINT (6834627.229 2342683.729)
4,n1692272423,1692272423,6.848312e+06,2.346883e+06,available,221,False,0.67,Begum Energy,Level 2,POINT (6848311.631 2346882.901)
...,...,...,...,...,...,...,...,...,...,...,...
1680,n11528393734,11528393734,6.670377e+06,2.505499e+06,available,120,True,0.26,Begum Energy,Level 1,POINT (6670377.267 2505499.361)
1681,n11533592971,11533592971,6.982196e+06,1.883888e+06,unavailable,480,True,0.45,Begum Energy,Level 3,POINT (6982196.454 1883887.506)
1682,n11534904116,11534904116,6.668169e+06,2.511348e+06,available,120,False,0.40,Tosuns Energy,Level 1,POINT (6668169.062 2511348.198)
1683,n11534904117,11534904117,6.668160e+06,2.511357e+06,unavailable,120,True,0.27,Begum Energy,Level 1,POINT (6668159.953 2511356.725)
1684,n11534904118,11534904118,6.668152e+06,2.511356e+06,unavailable,480,True,0.70,Eticanium Energy,Level 3,POINT (6668151.574 2511356.436)

In [18]:
gdf.to_csv("charging_stations_qgis.csv")